package com.github.uklance.mode;

import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.tapestry5.Link;
import org.apache.tapestry5.services.ComponentEventLinkEncoder;
import org.apache.tapestry5.services.ComponentEventRequestParameters;
import org.apache.tapestry5.services.Environment;
import org.apache.tapestry5.services.PageRenderRequestParameters;
import org.apache.tapestry5.services.Request;

import com.github.uklance.web.DelegateRequest;

/**
 * Allows a single page to render in multiple modes based on a URL prefix.
 * 
 * If the request URL contains a 'special' prefix it will be removed from the URL and passed to the
 * normal tapestry request processing. The special prefix will be used to construct a Mode instance which
 * is pushed onto the environment stack. Pages and components can then make decisions based on the Mode
 * 
 * The opposite is applied to outgoing URL's (eg links). If the Mode environmental is present, a prefix will
 * be added to the normal URL generated by tapestry.
 */
public class ModeComponentEventLinkEncoder implements ComponentEventLinkEncoder {
	private static final Pattern INBOUND_PATTERN = Pattern.compile("/([^/]*)(/.*)");
	private static final Pattern OUTBOUND_PATTERN = Pattern.compile("/([^/]*)/(.*)"); 
	private ComponentEventLinkEncoder delegate;
	private Set<String> specialPrefixes;
	private Environment environment;
	
	public ModeComponentEventLinkEncoder(ComponentEventLinkEncoder delegate, Environment environment, Set<String> specialPrefixes) {
		super();
		this.delegate = delegate;
		this.environment = environment;
		this.specialPrefixes = specialPrefixes;
	}
	
	public Link createPageRenderLink(PageRenderRequestParameters parameters) {
		return transform(delegate.createPageRenderLink(parameters));
	}
	public Link createComponentEventLink(ComponentEventRequestParameters parameters, boolean forForm) {
		return transform(delegate.createComponentEventLink(parameters, forForm));
	}
	public ComponentEventRequestParameters decodeComponentEventRequest(Request request) {
		return delegate.decodeComponentEventRequest(transform(request));
	}
	public PageRenderRequestParameters decodePageRenderRequest(Request request) {
		return delegate.decodePageRenderRequest(transform(request));
	}
	
	/**
	 * Applied to outgoing URL's
	 */
	private Link transform(Link link) {
		Mode mode = environment.peek(Mode.class);
		Link transformed = link;
		if (mode != null && mode.getMode() != null) {
			Matcher matcher = OUTBOUND_PATTERN.matcher(link.getBasePath());
			if (!matcher.matches()) {
				throw new RuntimeException("Illegal path " + link.getBasePath());
			}
			String newPath = String.format("/%s/%s/%s", matcher.group(1), mode.getMode(), matcher.group(2));
			transformed = link.copyWithBasePath(newPath);
		}
		return transformed;
	}

	/**
	 * Applied to incoming URL's
	 */
	private Request transform(Request request) {
		Request transformed = request;
		Matcher matcher = INBOUND_PATTERN.matcher(request.getPath());
		if (matcher.matches()) {
			String prefix = matcher.group(1);
			if (specialPrefixes.contains(prefix)) {
				environment.push(Mode.class, new ModeImpl(prefix));
				final String newPath = matcher.group(2);
				transformed = new DelegateRequest(request) {
					public String getPath() {
						return newPath;
					}
				};
			}
		}
		return transformed;
	}
}
